import React from 'react';
import Head from 'next/head';
import styles from './Header.module.css';

function Header(props) {
    return (
        <>
            <Head>
                <title>BlueTrade</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}></header>
            
        </>
    );
}

export default Header;